### ISSUE TITLE
Comply with semver

### ISSUE THREAD

**Issue by dobry-den** [koa-modules/swig#13]
https://github.com/koa-modules/swig/commit/b032d9088732042e58984616349d604633d11f6e

That's a breaking change.

You need to do a major version bump to `v2.x.x`.

May wanna patch `v1.x` to revert that so `npm install` won't break koa-swig for people unexpectedly.

**Comment by rakeshok** [comment]
+1 :/

**Comment by coderhaoxin** [comment]
@fundon +1 for this!

**Comment by fundon** [comment]
Sorry about that.
Yes, v1.x will keep the old way. I will submit a patch `v1.4.1`.

**Comment by fundon** [comment]
Fixed in `v1.5`.

**Comment by fundon** [comment]
The new way was landed in `v2.0`. 
Thank you!
