### ISSUE TITLE
Swig - No longer maintained

### ISSUE THREAD

**Issue by fundon** [koa-modules/swig#16]
https://github.com/paularmstrong/swig/issues/628

**Comment by coderhaoxin** [comment]
At this moment, I only use `React` :cry:

**Comment by fundon** [comment]
Both backend and frontend?

**Comment by coderhaoxin** [comment]
Yes

**Comment by fundon** [comment]
Cool! 🎆

**Comment by fundon** [comment]
@coderhaoxin 性能怎样，比普通的模板引擎效率高吗，所占内存如何？

**Comment by coderhaoxin** [comment]
这个到没对比过，主要是前后端统一模板的方便性。
